### ISSUE TITLE
Arreglar opacidad

### ISSUE THREAD

**Issue by meganIbague95** [MiguelMike93/PlusRecetas#14]
Arreglar contenido de texto de tal forma que no se confunda con el texto

**Comment by MiguelMike93** [comment]
Se aplico un poco de sobra a la letra que no se podía ver por la imagen de fondo y se le agrego un poco de opacidad para mejorar su visualización solucionado mediante el commit 7e2844e6e9ec70d0c5296c67edadad17cc7cfc56
