### ISSUE TITLE
Cargar imagen predeterminada

### ISSUE THREAD

**Issue by meganIbague95** [MiguelMike93/PlusRecetas#16]
En caso de que la imagen guardada no cargue, poner una predeterminada

**Comment by MiguelMike93** [comment]
se cargara una imagen predeterminada si la que se requiere no esta disponible en todos los casos sera un garfield Cocinando que hara referencia a la falta de imagen mediante el commit 434faa9127bb9d6ff29fbb1136e2b8076c90538a
