### ISSUE TITLE
Carga de comentarios con plugin

### ISSUE THREAD

**Issue by MiguelMike93** [MiguelMike93/PlusRecetas#3]
Al utilizar una sola pagina para cargar todas las recetas el plugin de facebook falla en diferenciar las recetas pues todas tienen la misma dirección 
<div class="fb-comments" data-href="http://recetas.epizy.com/recipe1.php?variable=$var" data-numposts="5"></div>

**Comment by MiguelMike93** [comment]
Ya que el plugin no reconoce la pagina por medio de la variable que se envía se sugiere cambiar el servicio de comentarios para las recetas.

**Comment by meganIbague95** [comment]
se creó el formulario de los comentarios y se agregan a la base de datos en el commit 8e0a078e98fa24bd943ded13b9d8db43dd74be62
